Grid
NagaSatyaGeeth/speed-cl pull request #31
Opened 2022-02-14 14:18 UTC by Artistole

https://hyvc6.csb.app
![ezgif com-gif-maker](https://user-images.githubusercontent.com/67518197/153881022-069ee226-e0a9-4550-827c-2a385b579539.gif)

2022-02-14 14:24 UTC, mohammed-sas approved these changes

2022-02-14 14:28 UTC, Husain01 approved these changes

2022-02-20 17:22 UTC, Tejinder15 requested changes
Hamburger menu not working aside is colliding with the main content on small screen.

2022-02-21 15:05 UTC, SubhamChoudhury approved these changes

2022-02-21 15:06 UTC, Artistole commented
> Hamburger menu not working aside is colliding with the main content on small screen.

sorry the csb link is old

2022-02-21 15:06 UTC, merged